//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CableManager.Localization.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Labels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Labels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CableManager.Localization.Resources.Labels", typeof(Labels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string DOC_Amount {
            get {
                return ResourceManager.GetString("DOC_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved by:.
        /// </summary>
        internal static string DOC_ApprovedBy {
            get {
                return ResourceManager.GetString("DOC_ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The offer serves only as invitation for payment.
        /// </summary>
        internal static string DOC_Bottom1 {
            get {
                return ResourceManager.GetString("DOC_Bottom1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value added tax declared (VAT 25%) can not be recognized as a pre-tax based on this offer.
        /// </summary>
        internal static string DOC_Bottom2 {
            get {
                return ResourceManager.GetString("DOC_Bottom2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controlled by:.
        /// </summary>
        internal static string DOC_ControlledBy {
            get {
                return ResourceManager.GetString("DOC_ControlledBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer tax number:.
        /// </summary>
        internal static string DOC_CustomerTaxNumber {
            get {
                return ResourceManager.GetString("DOC_CustomerTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date:.
        /// </summary>
        internal static string DOC_Date {
            get {
                return ResourceManager.GetString("DOC_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery date:.
        /// </summary>
        internal static string DOC_DeliveryDate {
            get {
                return ResourceManager.GetString("DOC_DeliveryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document composed by:.
        /// </summary>
        internal static string DOC_DocumentComposedBy {
            get {
                return ResourceManager.GetString("DOC_DocumentComposedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to email:.
        /// </summary>
        internal static string DOC_Email {
            get {
                return ResourceManager.GetString("DOC_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fax:.
        /// </summary>
        internal static string DOC_Fax {
            get {
                return ResourceManager.GetString("DOC_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISSUED BY:.
        /// </summary>
        internal static string DOC_IssuedBy {
            get {
                return ResourceManager.GetString("DOC_IssuedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mob:.
        /// </summary>
        internal static string DOC_Mobile {
            get {
                return ResourceManager.GetString("DOC_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string DOC_Name {
            get {
                return ResourceManager.GetString("DOC_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFER No:.
        /// </summary>
        internal static string DOC_OfferNumber {
            get {
                return ResourceManager.GetString("DOC_OfferNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string DOC_OrdinalNumber {
            get {
                return ResourceManager.GetString("DOC_OrdinalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone:.
        /// </summary>
        internal static string DOC_Phone {
            get {
                return ResourceManager.GetString("DOC_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string DOC_Price {
            get {
                return ResourceManager.GetString("DOC_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string DOC_Quantity {
            get {
                return ResourceManager.GetString("DOC_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebate %.
        /// </summary>
        internal static string DOC_Rebate {
            get {
                return ResourceManager.GetString("DOC_Rebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebate total:.
        /// </summary>
        internal static string DOC_RebateTotal {
            get {
                return ResourceManager.GetString("DOC_RebateTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax number:.
        /// </summary>
        internal static string DOC_TaxNumber {
            get {
                return ResourceManager.GetString("DOC_TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string DOC_Total {
            get {
                return ResourceManager.GetString("DOC_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total VAT:.
        /// </summary>
        internal static string DOC_TotalVAT {
            get {
                return ResourceManager.GetString("DOC_TotalVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total without VAT:.
        /// </summary>
        internal static string DOC_TotalWithoutVAT {
            get {
                return ResourceManager.GetString("DOC_TotalWithoutVAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        internal static string DOC_Unit {
            get {
                return ResourceManager.GetString("DOC_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT %.
        /// </summary>
        internal static string DOC_VAT {
            get {
                return ResourceManager.GetString("DOC_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worth until.
        /// </summary>
        internal static string DOC_WorthUntil {
            get {
                return ResourceManager.GetString("DOC_WorthUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string UI_About {
            get {
                return ResourceManager.GetString("UI_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string UI_Actions {
            get {
                return ResourceManager.GetString("UI_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string UI_Add {
            get {
                return ResourceManager.GetString("UI_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address to....
        /// </summary>
        internal static string UI_AddressTo {
            get {
                return ResourceManager.GetString("UI_AddressTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application for automatic offer creation based on customer request.
        /// </summary>
        internal static string UI_ApplicationAbout {
            get {
                return ResourceManager.GetString("UI_ApplicationAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank accounts.
        /// </summary>
        internal static string UI_BankAccounts {
            get {
                return ResourceManager.GetString("UI_BankAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        internal static string UI_Browse {
            get {
                return ResourceManager.GetString("UI_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable Manager.
        /// </summary>
        internal static string UI_CableManager {
            get {
                return ResourceManager.GetString("UI_CableManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable name.
        /// </summary>
        internal static string UI_CableName {
            get {
                return ResourceManager.GetString("UI_CableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonym names must be divided by comma [,].
        /// </summary>
        internal static string UI_CableNameAddInstruction {
            get {
                return ResourceManager.GetString("UI_CableNameAddInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable name already saved.
        /// </summary>
        internal static string UI_CableNameAlreadySaved {
            get {
                return ResourceManager.GetString("UI_CableNameAlreadySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable name must be entered.
        /// </summary>
        internal static string UI_CableNameMustBeEntered {
            get {
                return ResourceManager.GetString("UI_CableNameMustBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable name saved.
        /// </summary>
        internal static string UI_CableNameSaved {
            get {
                return ResourceManager.GetString("UI_CableNameSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cable not selected.
        /// </summary>
        internal static string UI_CableNotSelected {
            get {
                return ResourceManager.GetString("UI_CableNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cables not selected.
        /// </summary>
        internal static string UI_CablesNotSelected {
            get {
                return ResourceManager.GetString("UI_CablesNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string UI_ChangePassword {
            get {
                return ResourceManager.GetString("UI_ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string UI_City {
            get {
                return ResourceManager.GetString("UI_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string UI_Clear {
            get {
                return ResourceManager.GetString("UI_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string UI_Company {
            get {
                return ResourceManager.GetString("UI_Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company contact saved.
        /// </summary>
        internal static string UI_CompanyContactSaved {
            get {
                return ResourceManager.GetString("UI_CompanyContactSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        internal static string UI_ConfirmNewPassword {
            get {
                return ResourceManager.GetString("UI_ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM PASSWORD.
        /// </summary>
        internal static string UI_ConfirmPassword {
            get {
                return ResourceManager.GetString("UI_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string UI_Contact {
            get {
                return ResourceManager.GetString("UI_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        internal static string UI_Controls {
            get {
                return ResourceManager.GetString("UI_Controls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string UI_Country {
            get {
                return ResourceManager.GetString("UI_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string UI_Create {
            get {
                return ResourceManager.GetString("UI_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer Excel.
        /// </summary>
        internal static string UI_CreateOfferExcel {
            get {
                return ResourceManager.GetString("UI_CreateOfferExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer PDF.
        /// </summary>
        internal static string UI_CreateOfferPdf {
            get {
                return ResourceManager.GetString("UI_CreateOfferPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Croatian.
        /// </summary>
        internal static string UI_Croatian {
            get {
                return ResourceManager.GetString("UI_Croatian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currently logged in user:.
        /// </summary>
        internal static string UI_CurrentlyLoggedUser {
            get {
                return ResourceManager.GetString("UI_CurrentlyLoggedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        internal static string UI_CurrentPassword {
            get {
                return ResourceManager.GetString("UI_CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password is empty.
        /// </summary>
        internal static string UI_CurrentPasswordIsEmpty {
            get {
                return ResourceManager.GetString("UI_CurrentPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        internal static string UI_Customer {
            get {
                return ResourceManager.GetString("UI_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer must be selected.
        /// </summary>
        internal static string UI_CustomerMustBeSelected {
            get {
                return ResourceManager.GetString("UI_CustomerMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name already saved.
        /// </summary>
        internal static string UI_CustomerNameAlreadySaved {
            get {
                return ResourceManager.GetString("UI_CustomerNameAlreadySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer name must be entered.
        /// </summary>
        internal static string UI_CustomerNameMustBeEntered {
            get {
                return ResourceManager.GetString("UI_CustomerNameMustBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer request.
        /// </summary>
        internal static string UI_CustomerRequest {
            get {
                return ResourceManager.GetString("UI_CustomerRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer request document is successfully added.
        /// </summary>
        internal static string UI_CustomerRequestAdded {
            get {
                return ResourceManager.GetString("UI_CustomerRequestAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer request must be selected.
        /// </summary>
        internal static string UI_CustomerRequestMustBeSelected {
            get {
                return ResourceManager.GetString("UI_CustomerRequestMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer request must be in xlsx format.
        /// </summary>
        internal static string UI_CustomerRequestMustBeXlsx {
            get {
                return ResourceManager.GetString("UI_CustomerRequestMustBeXlsx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer saved successfully.
        /// </summary>
        internal static string UI_CustomerSaved {
            get {
                return ResourceManager.GetString("UI_CustomerSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer tax number must be entered.
        /// </summary>
        internal static string UI_CustomerTaxNumberMustBeEntered {
            get {
                return ResourceManager.GetString("UI_CustomerTaxNumberMustBeEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer tax number is already registered.
        /// </summary>
        internal static string UI_CustomerTaxNumberMustBeUnique {
            get {
                return ResourceManager.GetString("UI_CustomerTaxNumberMustBeUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string UI_Date {
            get {
                return ResourceManager.GetString("UI_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string UI_Delete {
            get {
                return ResourceManager.GetString("UI_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag &amp; Drop.
        /// </summary>
        internal static string UI_DragAndDrop {
            get {
                return ResourceManager.GetString("UI_DragAndDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string UI_Edit {
            get {
                return ResourceManager.GetString("UI_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UI_Email {
            get {
                return ResourceManager.GetString("UI_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string UI_English {
            get {
                return ResourceManager.GetString("UI_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter license.
        /// </summary>
        internal static string UI_EnterLicense {
            get {
                return ResourceManager.GetString("UI_EnterLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter license key.
        /// </summary>
        internal static string UI_EnterLicenseKey {
            get {
                return ResourceManager.GetString("UI_EnterLicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string UI_Fax {
            get {
                return ResourceManager.GetString("UI_Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string UI_FirstName {
            get {
                return ResourceManager.GetString("UI_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include in search.
        /// </summary>
        internal static string UI_IncludeInSearch {
            get {
                return ResourceManager.GetString("UI_IncludeInSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string UI_Language {
            get {
                return ResourceManager.GetString("UI_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string UI_LastName {
            get {
                return ResourceManager.GetString("UI_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is invalid.
        /// </summary>
        internal static string UI_LicenseIsInvalid {
            get {
                return ResourceManager.GetString("UI_LicenseIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License is valid, product is activated.
        /// </summary>
        internal static string UI_LicenseIsValid {
            get {
                return ResourceManager.GetString("UI_LicenseIsValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License key:.
        /// </summary>
        internal static string UI_LicenseKey {
            get {
                return ResourceManager.GetString("UI_LicenseKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load.
        /// </summary>
        internal static string UI_Load {
            get {
                return ResourceManager.GetString("UI_Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOG IN.
        /// </summary>
        internal static string UI_LogIn {
            get {
                return ResourceManager.GetString("UI_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string UI_Logo {
            get {
                return ResourceManager.GetString("UI_Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string UI_LogOut {
            get {
                return ResourceManager.GetString("UI_LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is possible to enter maximum five bank accounts.
        /// </summary>
        internal static string UI_MaxNumberOfBankAccountsIsFive {
            get {
                return ResourceManager.GetString("UI_MaxNumberOfBankAccountsIsFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string UI_Mobile {
            get {
                return ResourceManager.GetString("UI_Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UI_Name {
            get {
                return ResourceManager.GetString("UI_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string UI_NewPassword {
            get {
                return ResourceManager.GetString("UI_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password is empty.
        /// </summary>
        internal static string UI_NewPasswordIsEmpty {
            get {
                return ResourceManager.GetString("UI_NewPasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string UI_Note {
            get {
                return ResourceManager.GetString("UI_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cables deleted:.
        /// </summary>
        internal static string UI_NumberOfCablesDeleted {
            get {
                return ResourceManager.GetString("UI_NumberOfCablesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cables loaded:.
        /// </summary>
        internal static string UI_NumberOfCablesLoaded {
            get {
                return ResourceManager.GetString("UI_NumberOfCablesLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of customers deleted:.
        /// </summary>
        internal static string UI_NumberOfCustomersDeleted {
            get {
                return ResourceManager.GetString("UI_NumberOfCustomersDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of offers deleted:.
        /// </summary>
        internal static string UI_NumberOfOffersDeleted {
            get {
                return ResourceManager.GetString("UI_NumberOfOffersDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer.
        /// </summary>
        internal static string UI_Offer {
            get {
                return ResourceManager.GetString("UI_Offer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer document is not selected.
        /// </summary>
        internal static string UI_OfferDocumentNotSelected {
            get {
                return ResourceManager.GetString("UI_OfferDocumentNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer successfully saved.
        /// </summary>
        internal static string UI_OfferDocumentSaved {
            get {
                return ResourceManager.GetString("UI_OfferDocumentSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        internal static string UI_Open {
            get {
                return ResourceManager.GetString("UI_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overview.
        /// </summary>
        internal static string UI_Overview {
            get {
                return ResourceManager.GetString("UI_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PASSWORD.
        /// </summary>
        internal static string UI_Password {
            get {
                return ResourceManager.GetString("UI_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasword is empty.
        /// </summary>
        internal static string UI_PasswordIsEmpty {
            get {
                return ResourceManager.GetString("UI_PasswordIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password mismatch.
        /// </summary>
        internal static string UI_PasswordsMismatch {
            get {
                return ResourceManager.GetString("UI_PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed.
        /// </summary>
        internal static string UI_PasswordSuccessfullyChanged {
            get {
                return ResourceManager.GetString("UI_PasswordSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string UI_Phone {
            get {
                return ResourceManager.GetString("UI_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal code.
        /// </summary>
        internal static string UI_PostalCode {
            get {
                return ResourceManager.GetString("UI_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price list documents successfully loaded.
        /// </summary>
        internal static string UI_PriceDocumentsLoaded {
            get {
                return ResourceManager.GetString("UI_PriceDocumentsLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price lists.
        /// </summary>
        internal static string UI_PriceLists {
            get {
                return ResourceManager.GetString("UI_PriceLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebate (%).
        /// </summary>
        internal static string UI_Rebate {
            get {
                return ResourceManager.GetString("UI_Rebate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string UI_Save {
            get {
                return ResourceManager.GetString("UI_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select language:.
        /// </summary>
        internal static string UI_SelectLanguage {
            get {
                return ResourceManager.GetString("UI_SelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select at least one price list document.
        /// </summary>
        internal static string UI_SelectPriceListDocument {
            get {
                return ResourceManager.GetString("UI_SelectPriceListDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to customer.
        /// </summary>
        internal static string UI_SendToCustomer {
            get {
                return ResourceManager.GetString("UI_SendToCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string UI_Settings {
            get {
                return ResourceManager.GetString("UI_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGN UP.
        /// </summary>
        internal static string UI_SignUp {
            get {
                return ResourceManager.GetString("UI_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string UI_Status {
            get {
                return ResourceManager.GetString("UI_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        internal static string UI_Street {
            get {
                return ResourceManager.GetString("UI_Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUBMIT.
        /// </summary>
        internal static string UI_Submit {
            get {
                return ResourceManager.GetString("UI_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synonyms.
        /// </summary>
        internal static string UI_Synonyms {
            get {
                return ResourceManager.GetString("UI_Synonyms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax number.
        /// </summary>
        internal static string UI_TaxNumber {
            get {
                return ResourceManager.GetString("UI_TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string UI_User {
            get {
                return ResourceManager.GetString("UI_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User database is not created.
        /// </summary>
        internal static string UI_UserDatabaseIsNotCreated {
            get {
                return ResourceManager.GetString("UI_UserDatabaseIsNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UI_UserName {
            get {
                return ResourceManager.GetString("UI_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is already taken.
        /// </summary>
        internal static string UI_UserNameAlreadySigned {
            get {
                return ResourceManager.GetString("UI_UserNameAlreadySigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name is empty.
        /// </summary>
        internal static string UI_UserNameIsEmpty {
            get {
                return ResourceManager.GetString("UI_UserNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User number.
        /// </summary>
        internal static string UI_UserNumber {
            get {
                return ResourceManager.GetString("UI_UserNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User or password are incorrect.
        /// </summary>
        internal static string UI_UserOrPasswordNotCorrect {
            get {
                return ResourceManager.GetString("UI_UserOrPasswordNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully saved.
        /// </summary>
        internal static string UI_UserSuccessfullySaved {
            get {
                return ResourceManager.GetString("UI_UserSuccessfullySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User successfully signed up.
        /// </summary>
        internal static string UI_UserSuccessfullySignedUp {
            get {
                return ResourceManager.GetString("UI_UserSuccessfullySignedUp", resourceCulture);
            }
        }
    }
}
